create extension if not exists "pg_cron" with schema "pg_catalog";

create schema if not exists "pgmq";

create extension if not exists "pgmq" with schema "pgmq";

create schema if not exists "pgmq_public";


  create table "public"."processed_messages" (
    "id" bigint generated by default as identity not null,
    "message" character varying,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."processed_messages" enable row level security;

CREATE UNIQUE INDEX processed_messages_pkey ON public.processed_messages USING btree (id);

alter table "public"."processed_messages" add constraint "processed_messages_pkey" PRIMARY KEY using index "processed_messages_pkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION pgmq_public.archive(queue_name text, message_id bigint)
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$ begin return pgmq.archive( queue_name := queue_name, msg_id := message_id ); end; $function$
;

CREATE OR REPLACE FUNCTION pgmq_public.delete(queue_name text, message_id bigint)
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$ begin return pgmq.delete( queue_name := queue_name, msg_id := message_id ); end; $function$
;

CREATE OR REPLACE FUNCTION pgmq_public.pop(queue_name text)
 RETURNS SETOF pgmq.message_record
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$ begin return query select * from pgmq.pop( queue_name := queue_name ); end; $function$
;

CREATE OR REPLACE FUNCTION pgmq_public.read(queue_name text, sleep_seconds integer, n integer)
 RETURNS SETOF pgmq.message_record
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$ begin return query select * from pgmq.read( queue_name := queue_name, vt := sleep_seconds, qty := n , conditional := '{}'::jsonb ); end; $function$
;

CREATE OR REPLACE FUNCTION pgmq_public.send(queue_name text, message jsonb, sleep_seconds integer DEFAULT 0)
 RETURNS SETOF bigint
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$ begin return query select * from pgmq.send( queue_name := queue_name, msg := message, delay := sleep_seconds ); end; $function$
;

CREATE OR REPLACE FUNCTION pgmq_public.send_batch(queue_name text, messages jsonb[], sleep_seconds integer DEFAULT 0)
 RETURNS SETOF bigint
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$ begin return query select * from pgmq.send_batch( queue_name := queue_name, msgs := messages, delay := sleep_seconds ); end; $function$
;

grant delete on table "public"."processed_messages" to "anon";

grant insert on table "public"."processed_messages" to "anon";

grant references on table "public"."processed_messages" to "anon";

grant select on table "public"."processed_messages" to "anon";

grant trigger on table "public"."processed_messages" to "anon";

grant truncate on table "public"."processed_messages" to "anon";

grant update on table "public"."processed_messages" to "anon";

grant delete on table "public"."processed_messages" to "authenticated";

grant insert on table "public"."processed_messages" to "authenticated";

grant references on table "public"."processed_messages" to "authenticated";

grant select on table "public"."processed_messages" to "authenticated";

grant trigger on table "public"."processed_messages" to "authenticated";

grant truncate on table "public"."processed_messages" to "authenticated";

grant update on table "public"."processed_messages" to "authenticated";

grant delete on table "public"."processed_messages" to "postgres";

grant insert on table "public"."processed_messages" to "postgres";

grant references on table "public"."processed_messages" to "postgres";

grant select on table "public"."processed_messages" to "postgres";

grant trigger on table "public"."processed_messages" to "postgres";

grant truncate on table "public"."processed_messages" to "postgres";

grant update on table "public"."processed_messages" to "postgres";

grant delete on table "public"."processed_messages" to "service_role";

grant insert on table "public"."processed_messages" to "service_role";

grant references on table "public"."processed_messages" to "service_role";

grant select on table "public"."processed_messages" to "service_role";

grant trigger on table "public"."processed_messages" to "service_role";

grant truncate on table "public"."processed_messages" to "service_role";

grant update on table "public"."processed_messages" to "service_role";


  create policy "Enable insert for authenticated users only"
  on "public"."processed_messages"
  as permissive
  for insert
  to authenticated
with check (true);



